[package]
name = "scanner"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4.3"
pallas = "0.31.0"
tokio = { version = "1.42.0", features = ["rt-multi-thread", "tracing"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"
